# 公共配置文件
spring:
  application:
    name: user-center-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhao
    username: root
    password: 123456

  #  配置redis
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

  group-configs:
    - group: 'yu-pao'
      paths-to-match: '/**'
      packages-to-scan: com.zhao.usercenter.controller
knife4j:
    enable: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

